# Generated by Django 4.1.3 on 2022-11-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('BLACK', 'BLACK'), ('GOLD', 'GOLD')], max_length=30),
        ),
    ]
