# Generated by Django 4.1.3 on 2022-11-30 09:05

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('GOLD', 'GOLD'), ('BLACK', 'BLACK'), ('COPPER', 'COPPER'), ('GOLD STAINLESS STEEL', 'GOLD STAINLESS STEEL'), ('SILVER STAINLESS STEEL', 'SILVER STAINLESS STEEL'), ('COPPER PAINT', 'COPPER PAINT')], default=1, max_length=22),
            preserve_default=False,
        ),
    ]
