# Generated by Django 4.1.3 on 2022-11-30 09:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('60cm*60cm', '60cm*60cm'), ('90cm*90cm', '90cm*90cm'), ('100cm*100cm', '100cm*100cm'), ('70cm*70cm', '70cm*70cm'), ('80cm*80cm', '80cm*80cm')], max_length=19),
        ),
    ]
