# Generated by Django 4.1.3 on 2022-12-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_order_alter_product_colors_alter_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.CharField(choices=[('GOLD', 'GOLD'), ('BLACK', 'BLACK'), ('COPPER', 'COPPER'), ('GOLD STAINLESS STEEL', 'GOLD STAINLESS STEEL'), ('SILVER STAINLESS STEEL', 'SILVER STAINLESS STEEL'), ('COPPER PAINT', 'COPPER PAINT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('60cm*60cm', '60cm*60cm'), ('90cm*90cm', '90cm*90cm'), ('100cm*100cm', '100cm*100cm'), ('70cm*70cm', '70cm*70cm'), ('80cm*80cm', '80cm*80cm')], max_length=50),
        ),
    ]
