# Generated by Django 4.1.3 on 2022-12-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_product_colors_alter_product_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default=1234567890),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default=1234567, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default=123456, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default=1234567, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='postal',
            field=models.IntegerField(default=12345678),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default=1234567, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=1234567, max_length=50),
            preserve_default=False,
        ),
    ]
