# Generated by Django 4.1.3 on 2022-12-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='save',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
